### ISSUE TITLE
notEq Proposal

### ISSUE THREAD

**Issue by dhershman1** [dhershman1/kyanite#104]
## notEq

**Signature(s):**
`a -> b -> Boolean`

**Type:** `Function`

Takes two values and compares them, returns depending on if the values are equal or not

### Why

This will complement to the `eq` function we already have

### Syntax

**Parameters:**
`a` - `Any`: The first value to compare
`b` - `Any`: The second value to compare

```js
K.notEq(a, b)
```

### Usage

```js
K.notEq(1, 2) // => true
K.notEq(2, 2) // => false
```

### Additional Info

This will NOT compare like the `deepEq` this will work strictly the same as `eq`.

I am also hesitant atm because this is literally just `K.compose(K.not, K.eq(a), b)` so it's just a syntax sugar addition for a pretty easy setup. So thoughts would be appreciated!

**Comment by hamidyou** [comment]
I think there are enough use cases to warrant making this its own thing.

**Comment by dhershman1** [comment]
Added to the v0.12.2 development branch
