### ISSUE TITLE
propEq Proposal

### ISSUE THREAD

**Issue by dhershman1** [dhershman1/kyanite#105]
## propEq

**Signature(s):**
`String -> Any -> Object -> Boolean`

**Type:** `Object`

Accepts a prop, value, and a Object it finds the that prop within the object and then compares it against the provided value.

### Why

This will compliment our growing equals functionality

### Syntax

**Parameters:**
`p` - `String`: The Prop to look for
`val` - `Any`: The value it is compared against
`obj` - `Object`: The object to use

```js
K.propEq(p, val, obj)
```

### Usage

```js
K.propEq('suit', 'club', { suit: 'club' }) // => true
K.propEq('suit', 'club', { suit: 'spade' }) // => false

// Curried

const isClub = K.propEq('suit', 'club')

isClub({ suit: 'club' }) // => true
isClub({ suit: 'spade' }) // => false
```

### Additional Info

This is additional syntax sugar for doing something like this:

`(p, val) => K.compose(K.eq(val), K.prop(p))`

**Comment by hamidyou** [comment]
YES!

**Comment by dhershman1** [comment]
Currently added to the v0.12.2 development branch.
