### ISSUE TITLE
Misleading Return for and & or functions

### ISSUE THREAD

**Issue by dhershman1** [dhershman1/kyanite#108]
**Describe the bug**
So currently it is stated that `and` & `or` return Booleans back after processing. But in turn they do not, they return whatever the truthy value is. (see below for examples)

**To Reproduce**
1. Open a new JS file
2. Import `and` & `or`
3. Run the functions with non boolean types

**Expected behavior**
I am unsure, actually. This behavior is much more like the default behavior of core JavaScript. So we need to make the choice, is the bug in the documentation or is the bug in the functions?

**Comment by hamidyou** [comment]
I say bug in the functions. They should be booleans.

**Comment by dhershman1** [comment]
This has been addressed in the development branch for v0.12.2, The documentation has been adjusted to what the function is doing.
