### ISSUE TITLE
Remove Spread from apply Function

### ISSUE THREAD

**Issue by dhershman1** [dhershman1/kyanite#110]
Currently the `apply` function has a spread operator applied to it

I don't like this, it limits the ability to just use apply as a shorter `compose` for stuff like `pipes`, `branches`, etc...

What I am thinking is instead of it being:
```js
const apply = (fn, a) => fn(...a)
```

It should just be:
```js
const apply = (fn, a) => fn(a)
```

And then we can create a **new** function called something like `applyN` which can run the spread operator.

Option 2 is to leave it which means any time you want to call `apply` you're gonna need to make sure the data is wrapped in an array

Options 3 is to expand `apply` so it can also handle an Array this is the least likely to happen since that means the function would intentionally be multi typed.

This is obviously a breaking change if anything. So it would need to be a part of v0.13.0

Thoughts?

**Comment by hamidyou** [comment]
Option 1 seems to align with the pattern of the rest of the library. I say change it to that.

**Comment by dhershman1** [comment]
this has been added to v1.0.0 for release
