### ISSUE TITLE
fold Proposal

### ISSUE THREAD

**Issue by dhershman1** [dhershman1/kyanite#113]
## fold

**Signature(s):**
`(a -> b) -> Array [a] -> b`

**Type:** `Array`

Takes a function and an array of data and runs that function against the values in the array to generate a new value.

### Why

`fold` will work a lot like `reduce` however fold would only take 2 parameters the accumulator would not be provided here. Sometimes this type of reduce is handy and works well for things like a `min` function.

### Syntax

**Parameters:**
`fn` - `Function`: The predicate function to run against each value
`arr` - `Array`: The array we want to fold

```js
K.fold(fn, arr)
```

### Usage

```js
const min = K.fold((acc, a) => a <= acc ? a : b)

min([1, 3, 2, 5, 4]) // => 1
```

### Additional Info (Optional)

This can be applied as well where I have to use the vanilla reduce for certain situations where I don't require an accumulator.

**Comment by hamidyou** [comment]
Since min already exists can you give another use case/example?

**Comment by dhershman1** [comment]
This would replace what `min` currently does, which is:

`const min = list => list.reduce((a, b) => a <= b ? a : b)`

I can't use Kyanites reduce here like I can with `max` because Kyanites reduce ALWAYS needs an initial accumulator value.

**Comment by dhershman1** [comment]
fold is added to dev branch and ready for v0.13.0 release
