### ISSUE TITLE
match Proposal

### ISSUE THREAD

**Issue by dhershman1** [dhershman1/kyanite#114]
## match

**Signature(s):**
`Array (a -> Maybe b) -> a -> Maybe b`

**Type:** `Function`

Contains a list of functions that return a value or `undefined`, works well with `when`, `unless`, and `branch`. Provide a function that always returns a value at the end, to avoid the case where no matches are found.

### Why

This works similar to a pipe, or a short circuited reduce function on a array of functions. There have been multiple occasions where I found something like this might be useful

### Syntax

**Parameters:**
`fns` - `Array`: The array of functions to sift through
`val` - `Any`: The value to pass to each function

```js
K.match(fns, val)
```

### Usage

```js
const fn = K.match([
  K.when(K.lt(10), K.inc),
  K.when(K.gt(10), K.dec),
  K.when(K.always(true), K.identity)
])

fn(1) //=> 2

fn(15) //=> 14

fn(10) //=> 10
```

### Additional Info

The name of this function is still up for debate since there is a regexp function also called `match`

Potential names:
- pair

**Comment by hamidyou** [comment]
I like this. Agree that the name could be more descriptive. Also, in the example why is the third function needed?

**Comment by dhershman1** [comment]
To always return something, otherwise it returns `undefined` so if you want the function to always formulate to a default value of some kind always make sure to have a function at the very end to specify that.

**Comment by dhershman1** [comment]
Closing in favor of the `done` (#117) proposal
