### ISSUE TITLE
either Doesn't always return Boolean

### ISSUE THREAD

**Issue by dhershman1** [dhershman1/kyanite#127]
**Describe the bug**
The `either` function doesn't always return a Boolean as the signature would suggest. It might return actual data. This is probably because either is just using the `||` operator.

**To Reproduce**
1. Create a simple object `{ foo: [1], bar: [2] }`
2. Give it to the `either` function like so:
```
const data = { foo: [1], bar: [2] }

K.either(K.prop('foo'), K.prop('bar'), data)
```
3. The return will most likely be `[1]` instead of a boolean `true`

**Expected behavior**
We should be getting back a `Boolean` instead of `Any`

**Screenshots**
Not Needed

**Desktop (please complete the following information):**
Not Needed

**Additional context**
This may be up for debate, do we want either to always return a Boolean? Granted the values it gives back will _always_ be truthy or falsy but it's worth a debate I suppose.

Though after I built out these examples and stuff I am sort of liking the idea of keeping it so it returns the data and updating the Signature instead of forcing it to return a Boolean.

**Comment by dhershman1** [comment]
The signature is fine and I believe the way this function acts is correct and fine.

**Comment by hamidyou** [comment]
I am confused on a use case.  Any chance you could provide more examples?
