### ISSUE TITLE
quotient Proposal

### ISSUE THREAD

**Issue by dhershman1** [dhershman1/kyanite#129]
## quotient

**Signature(s):**
`Array [Number] -> Number`

**Type:** `Number`

Takes an array of numbers and tries to get a quotient from the list

### Why

We have a `sum` and `product` function why not have one for division as well?

### Syntax

**Parameters:**
`arr` - `Array`: The array of numbers to divide down

```js
K.quotient(arr)
```

### Usage

```js
K.quotient([2, 1, 2]) // => 1
```

### Additional Info

Do we add logic to handle divide by 0 possibilities? If so how do we handle that, do we throw an error, skip the number, or something else?

**Comment by hamidyou** [comment]
I like the concept and yes, we need to handle zero....return error "cannot divide by zero"?
