### ISSUE TITLE
diff Proposal

### ISSUE THREAD

**Issue by dhershman1** [dhershman1/kyanite#130]
## diff/difference

**Signature(s):**
`Array [Number] -> Number`

**Type:** `Number`

Takes an array of numbers and subtracts them to find the difference

### Why

We already have a `sum` and `product` function so why not add in a `difference`?

### Syntax

**Parameters:**
`arr` - `Array`: The array of numbers to get the difference of

```js
K.diff(arr)
// OR
K.difference(arr)
```

### Usage

```js
K.diff([5, 1, 2]) // => 2
// OR
K.difference([5, 1, 2]) // => 2
```

### Additional Info (Optional)

Obviously this one is up in the air, we already have a `difference` function which gets the difference in arrays.

So do we name this one `diff`? Or rename the array `difference` instead in order to name this one `difference`?

**Comment by hamidyou** [comment]
totalDiff?
