### ISSUE TITLE
propOr doesn't like null

### ISSUE THREAD

**Issue by dhershman1** [dhershman1/kyanite#144]
**Describe the bug**
`propOr` is falling over on null values, this feels like a deja vu bug?

**To Reproduce**
1. import `propOr`
2. Pass it null, example: `propOr('', ['name'], null)`

**Expected behavior**
I believe propOr should return the default value on a null just like it would for undefined

**Comment by Glen-Cocoa** [comment]
I'm having trouble reproducing, when i pass in null object propOr throws an error because it's trying to read a property off an object that doesn't exist. Seems to function as I would expect when the value stored at the accessed property is both null and undefined.

**Comment by Glen-Cocoa** [comment]
So are you suggesting that when the accessed object doesnt exist, propOr should still return the default value?

**Comment by dhershman1** [comment]
correct, in my opinion it should behave the same as `pathOr` which reads the object and if that object does not exist (undefined or null) it returns the defaulted value.

**Comment by Glen-Cocoa** [comment]
made a PR to fix behavior [here](https://github.com/dhershman1/kyanite/pull/145/files)
