### ISSUE TITLE
[IE11 support] Add ES5 compatible build

### ISSUE THREAD

**Issue by AndrewBogdanovTSS** [dhershman1/kyanite#149]
**Describe the bug**
Kyanite is not compatible with ES5 browsers such as IE11. It throws a syntax error SCRIPT1002 and also SCRIPT5007: Object expected

**To Reproduce**
1. Add kyanite to the page
2. Open it in IE11 

**Expected behavior**
Kyanite code should be transpiled to ES5 compatible code. No errors in the console should be present.

**Desktop (please complete the following information):**
 - Windows 10
 - IE11

**Repro Link**
https://jsbin.com/nocuxit/edit?html,console,output

**Comment by dhershman1** [comment]
IE11 compatible build is on its way out the door soon. (#150)
