### ISSUE TITLE
path documentation spelling error

### ISSUE THREAD

**Issue by hamidyou** [dhershman1/kyanite#15]
In the documentation for the kyanite.path() function, the word "undefined" is misspelled under "Returns"
![screen shot 2018-09-17 at 5 50 10 pm](https://user-images.githubusercontent.com/23492367/45652293-2ac7b700-baa2-11e8-8882-cb12ff160d22.png)

**Comment by dhershman1** [comment]
This will be addressed in v0.8.1 after a few other tweaks are done. Thanks for pointing it out!

**Comment by dhershman1** [comment]
This will be a part of the v0.9.0 release. Added to the appropriate milestone, and is currently active and working on the development branch.
