### ISSUE TITLE
New Modularity Level

### ISSUE THREAD

**Issue by dhershman1** [dhershman1/kyanite#16]
The ability to request functions is great, but it might also be helpful to have the ability to require by type

For instance:

```js
import KA from 'kyanite/array' 

KA.first([1, 2, 3])
KA.uniq([1, 1, 2, 2, 3, 3])
```

**Comment by dhershman1** [comment]
This is currently added and working on the development branch

**Comment by hamidyou** [comment]
I like this idea.  Personally, I would always want the full library, but this would still be a good feature that allows personal customization
