### ISSUE TITLE
[BREAKING] Change Variable given to script tags

### ISSUE THREAD

**Issue by dhershman1** [dhershman1/kyanite#17]
I want to change the name given to the script tags to be more shorthand friendly by default

This is obviously a high level in terms of breaking changes. It would work something like this:

```html
<script src="https://cdn.jsdelivr.net/npm/kyanite@latest/dist/kyanite.min.js"></script>
<script>
  // The variable K would now contain the library functions
  K.isEmpty({})
</script>
```

This is not a API/functionality change mainly a naming change in the long run

So we'd be looking at something like `kyanite.isEmpty({}) -> K.isEmpty({}`

**Comment by dhershman1** [comment]
This is currently done and working on the development branch

**Comment by hamidyou** [comment]
Would this make "k" the default instead of "kyanite" used to call one of the kyanite functions?

**Comment by dhershman1** [comment]
> Would this make "k" the default instead of "kyanite" used to call one of the kyanite functions?

Yes, so you would use `K` instead of `kyanite` when calling a function.

for example: `kyanite.isEmpty({})` -> `K.isEmpty({})`

**Comment by dhershman1** [comment]
I think i am going to reverse this for now. I don't see enough benefit other than not having to type out several extra characters.

When using a script tag you can just as easily do 

`const k = kyanite` anyway, which gives you the same effect.

**Comment by dhershman1** [comment]
I think we are gonna stick with what we have, and continue to give kyanite since its not as generic as K for a global.

Less worry about breaking stuff too.
