### ISSUE TITLE
isEqual order

### ISSUE THREAD

**Issue by dhershman1** [dhershman1/kyanite#24]
Should `isEqual` take into consideration the order of an array/object?

For example:

`[9, 0, 0, 9]` vs `[0, 9, 0, 9]` Technically they contain the same value but not the same order.

Should this be a thing?

**Comment by hamidyou** [comment]
What about adding a 3rd parameter for strict?  If you want the equal of an array to be exact (same indices) then you can add a third parameter.  Maybe set default to false so that it would function as designed by default. If user wants strict, they can add true as the 3rd param.

**Comment by dhershman1** [comment]
I am leaning more towards just making isEqual return false if the array is out of order since technically speaking the arrays have different values at that point. I'd rather avoid adding a 3rd param if I am capable.

**Comment by hamidyou** [comment]
got it....I was having a hard time coming up with a time when you would want to consider two arrays with numbers at different indices equal, but I also wasn't sure if there was functionality in that to which I was unaware

**Comment by dhershman1** [comment]
Since it only makes sense to consider it, v0.9.0 of Kyanite will adjust the functionality of `isEqual` to take into account the order of arrays rather than just their length & values within.

**Comment by dhershman1** [comment]
`isEqual` will now take into consideration the order of an array when comparing it in v0.9.0
