### ISSUE TITLE
Scrolling Window

### ISSUE THREAD

**Issue by hamidyou** [dhershman1/kyanite#26]
It is frustrating when the screen scrolls all the way up and then I need to scroll all the way down to look at the next function. It happens a lot when I am looking through to see what is available.

**Describe the solution you'd like**
The function documentation window shows up wherever the page is, not just at the top.

**Describe alternatives you've considered**
I just deal with it.  It isn't that big of a deal

**Comment by dhershman1** [comment]
I like this idea a lot. Can you open this issue on my website repo instead?

https://github.com/dhershman1/dusty-codes-site/issues
