### ISSUE TITLE
includedWith proposal

### ISSUE THREAD

**Issue by dhershman1** [dhershman1/kyanite#28]
**Name is up for debate, probably change to something a little easier to understand**

**Is your feature request related to a problem? Please describe.**
No, more along the lines of expanding upon the includes functionality, currently is handles simple types just like it should, I'd like to expand upon it to handle complex types too (through a new function)

**Describe the solution you'd like**
Skim through an array and run a function on the values, if the value returns true then the includes will be true, otherwise false

**Describe alternatives you've considered**
N/A

**Additional context**
The use case would work something like this:

```js
import includedWith from 'kyanite/includedWith'

includedWith(x => x.isThing, [{ isThing: false }, { isThing: true }]) // => true
includedWith(x => x.isThing, [{ isThing: false }]) // => true
includedWith(x => x.isThing, [{ isOtherThing: false }, {}]) // => false
```

Obviously this would also mean it would be curried.

```js
import includedWith from 'kyanite/includedWith'

const in = includedWith(x => x.foo)

in([{ foo: 1 }]) // => true 
```

**Comment by hamidyou** [comment]
would this replace the includes?  If so, I like the idea as it would allow for distinction from the vanilla js includes

**Comment by dhershman1** [comment]
Nope this would be it's own new method that works along side includes

**Comment by hamidyou** [comment]
I like it

**Comment by dhershman1** [comment]
This is essentially the same as `some` and not needed.
