### ISSUE TITLE
either Proposal

### ISSUE THREAD

**Issue by dhershman1** [dhershman1/kyanite#35]
## either

**Signature(s):**
`(a -> Boolean) -> (a -> Boolean) -> a -> Boolean`

**Type:** `Function`

Much like the `both` but rather than needing to be true, either is capable to be true in this case.

### Why

Expanding upon the logic base of the library to easily apply logic functions on complex data types or complex logic

### Syntax

```js
K.either(fn, fn, data)
```

### Usage

```js
K.either(x => x > 2, x => x > 0, 4) // => true

const fn = K.either(x => x > 2, x => x > 0)

fn(10) // => true
fn(-1) // => false
```

**Comment by hamidyou** [comment]
is the only difference between this and k.or() that you can also pass data to this as a parameter?

**Comment by dhershman1** [comment]
> is the only difference between this and k.or() that you can also pass data to this as a parameter?

More so that you can run functions on the data, so its like or in the sense of:

`K.either(fn1, fn2, data) === K.or(fn1(data), fn2(data))`

**Comment by dhershman1** [comment]
either has been added for the v0.9.0 release
