### ISSUE TITLE
takeWhile Proposal

### ISSUE THREAD

**Issue by dhershman1** [dhershman1/kyanite#38]
## takeWhile

**Signature(s):**
`(a -> Boolean) -> Array [a] -> Array [b]`

**Type:** `Array`

Sort of like drop while but the opposite, this will take values and put them into a new array while the function passed in returns true

### Why

We currently have a `take` function which requires an index and it will grab the value from the array. This will take based on a function which helps expand its usability.

### Syntax

```js
K.takeWhile(fn, data)
```

### Usage

```js
K.takeWhile(x => x < 4, [1, 2, 3, 4, 5, 6]) // => [1, 2, 3]

const fn = K.takeWhile(x => x < 4)

fn([1, 2, 3, 4, 5]) // => [1, 2, 3]
fn([3, 4, 5]) // => [3]
```

**Comment by hamidyou** [comment]
This is what I was trying to go for....I love this.....would I be able to pass in a map or filter and have the map or filter stop?

**Comment by dhershman1** [comment]
Not necessarily, this runs a function against the values if it passes it will be placed into a new array as is. You can then run a map against the new array itself if you'd like however, so you only map the values you want within that array.

```js
K.map(K.mul(2), K.takeWhile(K.gt(1), [1, 2, 3, 4])) // => [4, 6, 8]

// Or in a pipe:

K.pipe([
  K.takeWhile(K.gt(1)),
  K.map(K.mul(2))
], [1, 2, 3, 4]) // => [4, 6, 8]
```

**Comment by hamidyou** [comment]
Oooh....I like that.

**Comment by dhershman1** [comment]
This has been pushed up to the development branch and is prepped and ready for the v0.9.0 release
