### ISSUE TITLE
split Proposal

### ISSUE THREAD

**Issue by dhershman1** [dhershman1/kyanite#43]
## split

**Signature(s):**
`String -> Array`

**Type:** `String`

Takes a string and splits it down into an array based on the value based by the user

### Why

This gives a curried and pipe friendly split function to the user

### Syntax

```js
K.split(splitBy, str)
```

### Usage

```js
K.split(':', '122:223') // => ['122', '223']

const sp = K.split(':')

sp('122:223') // => ['122', '223']
sp('335:7756') // => ['335', '7756']
```

**Comment by hamidyou** [comment]
Would  the following work as well?

`K.split('', 'hello') // => ['h', 'e', 'l', 'l', 'o']`

**Comment by dhershman1** [comment]
> 
> 
> Would the following work as well?
> 
> `K.split('', 'hello') // => ['h', 'e', 'l', 'l', 'o']`

Correct it would act the same

**Comment by dhershman1** [comment]
Split has been added to the development branch for the v0.9.0 release candidate.
