### ISSUE TITLE
Expand upon basic functions like and

### ISSUE THREAD

**Issue by dhershman1** [dhershman1/kyanite#54]
So maybe it'd be a cool idea to expand upon the current functionality of stuff like `and`, `or` etc... 

By expand I mean have them run the ability to accept multiple params currently both are restricted to two parameters.

current:

`K.and(bool1, bool2)`
`K.or(bool1, bool2)`

My proposition is to extend on this functionality like so:

`K.and(bool1, bool2, bool3, booln)`
`K.or(bool1, bool2, bool3, booln)`

This same extension could be applied to functionality like `add`, `sub`, `mul`, etc etc... 

This allows us to also follow more closely to the Clojure style and flow of doing things. Which would be really super cool and good.

**Comment by hamidyou** [comment]
again, yes please!

**Comment by dhershman1** [comment]
Both `and` & `or` are able to accept as many arguments as needed now. There are not many options outside of these for the same idea
