### ISSUE TITLE
Expand upon numeric functions

### ISSUE THREAD

**Issue by dhershman1** [dhershman1/kyanite#55]
Much like the ticket #54 I think it would be beneficial to expand the mathematical functions as well. For example:

Currently the functionality works like so:
```js
K.add(first, second)
```

The proposed change is to offer more of a "accept as many numbers" situation.
```js
K.add(first, second, third, ...nth)
```

This isn't limited to just the `add` and `sub` functions but also the other pieces of functionality.

Opening up the field for things like:
```js
const data = [1, 2, 3, 4]

K.add(...data) // => 10
```

This also falls in line with the way clojure does a lot of its mathematical functions/operators

**Comment by hamidyou** [comment]
yes please!  This would be great!

**Comment by dhershman1** [comment]
This isn't really required and is a rather large overkill and performance hit for these functions since you can easily just do something like:

```js
[1, 2, 3].reduce(K.add, 0)
```
