### ISSUE TITLE
Scrapping the Modularity System

### ISSUE THREAD

**Issue by dhershman1** [dhershman1/kyanite#61]
Currently the libraries modularity is fairly strong.

However Rollups treeshaking capabilities have gotten much much better. The original reason behind the modular aspects of the library was to address an issue with the build tool.

Previously, Treeshaking didn't take into account curried functions. So even if you would destructure only a few functions, you'd also get all of the curried functions with it.

This is no longer a problem as it seems the treeshaking capabilities easily handles curried functions now. Which begs the question: **Do we need to have function modularity through out the lib still?**

Pros:
- Build improvements
- Light weight packaging
- No longer a need to import each function individually, or by category
- Adding a module support prop lets ES6 based apps easily import functions

Cons:
- This removes the ability for script tags to only bring in a category or a single function
  - Is that really an issue though? If they need to script tag a single function They will find something else or build it themselves I'd assume?
- The above only works if you're using a build tool with treeshake capabilities (Rollup, or Webpack v2+, etc)

The answer is: **No**. No we don't. We can easily guide non ES6 apps to the library with CommonJS. And ES6+ apps can also use the module version (which points to the index.js). Destructuring can take it from there without a worry.

**Comment by Glen-Cocoa** [comment]
8^)

**Comment by dhershman1** [comment]
Modularity has been taken out and major optimizations thanks to it. Ready for a v0.10.0 release
