### ISSUE TITLE
Do we drop support for IE?

### ISSUE THREAD

**Issue by dhershman1** [dhershman1/kyanite#68]
So as the flow of technology goes on its harder and harder to deny the want to use more of the newer functionality without having to re write it to work for IE.

Currently Kyanite supports IE 10+ (maybe 9 but I don't think so anymore)

It's hard to support different Data because of IE. We have to transpile down and bloat the code base because of IE.

It'd be nice to go full ES6 in the form that Kyanite also uses the methods from ES6, this would make using a lot of different things much easier, and perhaps slim down the library. This would also remove the need to be careful about every single feature ever added.

But of course that means cutting IE out of the picture and anyone who has to actively support it that for some reason wanted to use Kyanite would be unable.

**Comment by hamidyou** [comment]
You have my full support to cutout IE support......OR can you keep a KyaniteIE and leave it at .9 . State that it isn't supported beyond that version..?

**Comment by smoaty** [comment]
I think the above comment has a great idea. Have a version that supports IE (I suppose that would just be leaving it in it's current form) and having all future updates and versions warn that IE isn't supported.

**Comment by dhershman1** [comment]
From issue #72 stand point I see no reason to continue support for IE. Especially if we want to integrate some neat `Map` & `Set` data type functionality into the lib.

Since underscore is still banging and is a very great library IE should be covered. No need to stick around here.
