### ISSUE TITLE
Breakdown isEqual

### ISSUE THREAD

**Issue by dhershman1** [dhershman1/kyanite#7]
The function `isEqual` is a very heavy function. It's one of the biggest within Kyanite.

However this function is capable of comparing a vast majority of types to make sure they're strictly equal to one another.

But, is this really necessary? I don't usually come across a need to compare some of the more complex types that are floating about. 

A possible theory/solution:
Breakdown `isEqual` into comparison functions among the types. For example:

Each of these would be separate new functions:

- A new function to compare objects
- A new function to compare arrays
- A generic function to compare simple types (numbers, strings, booleans)
- Possibly a new function for some special cases if needed?
  - If this is the case depending. Maybe this solution isn't worth it then?

The idea here is to make things smaller and remove the need for such a hefty function like `isEqual`

Thoughts?

**Comment by justin-lyon** [comment]
What if you broke it down into these smaller implementations, but update the current isEquals so it uses the new isolated implementations?

Then consumers of this library can import exactly what they need, including the massive isEquals should they so choose.

**Comment by dhershman1** [comment]
Decided to strip the isEqual functionality down.

It can still handle the essentials: `Boolean`, `Number`,  `String`, `Object`, `Array`, `Date`, `RegExp`, and memory like `Promise` types.

However it does not handle when you specify content such as `Booleans` using `new Boolean(true)` since technically speaking `true !== new Boolean(true)`

This does not directly apply to items such as `RegExp` since technically speaking

`/[A-Z]/ === new RegExp('[A-Z]')` Since one is just a short hand for the function call

**Comment by hamidyou** [comment]
I like the stripped down functionality into their own functions by type.   Would it handle RegExp?
