### ISSUE TITLE
New Proposal List

### ISSUE THREAD

**Issue by dhershman1** [dhershman1/kyanite#92]
A small gathering of proposed functionality that may or may not be useful.

(Mainly some notes on functions that might be worth adding or not, so I don't forget!)

- [ ] ~`sqrt` - Works basically like `Math.sqrt`~
- [x] `sum` - Takes an array of numbers and adds them together
- [x] `product` - Takes an array of numbers and multiplies them together

I am not sure if I want to do something like `quotient` for division or something for subtraction simply because of respecting order of operations might be annoying here.

**Comment by hamidyou** [comment]
I am all for mathematical operations

**Comment by dhershman1** [comment]
Removing the sqrt idea, after putting it on paper I think it's rather pointless in purpose.

**Comment by dhershman1** [comment]
`sum` and `product` have been added to the development branch and should be ready to go.
